openapi: 3.1.0

info:
  title: User API
  description: This is the API of the User service
  license:
    name: GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.0

tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
paths:
  /:
    get:
      tags:
      - developers
      summary: home page of the service
      operationId: home
      responses:
        "200":
          description: welcome message
          content:
            text/html:
              schema:
                type: string
  /users:
    get:
      tags:
        - developers
      summary: get the full JSON users database
      operationId: get_users
      responses:
        "200":
          description: full JSON
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllUsers'

  /users/{userid}:
    get:
      tags:
        - developpers
      summary: get the JSON of a user from the userid
      description: By passing in an existing userid, you can get the details of a user
      operationId: gets_user_by_id
      parameters:
      - name: userid
        in: path
        description: User ID.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Details of the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: bad input parameter
        

    post:
      tags:
        - admins
      summary: Adds a new user
      description: Adds a new user
      operationId: add_user
      parameters:
      - name: userid
        in: path
        description: User ID.
        required: true
        style: simple
        explode: false
        schema:
          type: string

      
components:
  schemas:
    AllUsers:
      required:
      - user
      type: object
      properties:
        user: 
          type: array
          items:
            $ref: '#/components/schemas/User'
    User:
      required:
      - id
      - name
      - last_active
      type: object
      properties:
        id:
          type: string
          example: "jim_halpert"
        name:
          type: string
          example: "Jim Halpert"
        last_active:
          type: integer
          example: 1360031325
