openapi: 3.1.0

info:
  title: User API
  description: This is the API of the User service
  license:
    name: GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.0

tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
paths:
  /:
    get:
      tags:
      - developers
      summary: home page of the service
      operationId: home
      responses:
        "200":
          description: welcome message
          content:
            text/html:
              schema:
                type: string
  /users:
    get:
      tags:
        - developers
      summary: get the full JSON users database
      operationId: get_users
      responses:
        "200":
          description: full JSON
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllUsers'

  /users/{userid}:
    get:
      tags:
        - developers
      summary: get the JSON of a user from the userid
      description: By passing in an existing userid, you can get the details of a user
      operationId: gets_user_by_id
      parameters:
      - name: userid
        in: path
        description: User ID.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Details of the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: bad input parameter
        

    post:
      tags:
        - admins
      summary: Adds a new user
      description: Adds a new user
      operationId: add_user
      parameters:
      - name: userid
        in: path
        description: User ID.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: username
        in: body
        description: User name
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Details of the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: User id already exists

  /users/{userid}/movies:
    get:
      tags:
        - developers
      summary: get the JSON of a user's movies that he booked from the userid
      description: By passing in an existing userid, you can get the details of a user's booked movies
      operationId: get_user_movies_by_id
      parameters:
      - name: userid
        in: path
        description: User ID.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Details of the user's movies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllMovies'
        "400":
          description: bad input parameter

    delete:
      tags:
      - admins
      summary: delete specified user
      description: delete specified user
      operationId: delete_user
      parameters:
      - name: userid
        in: path
        description: User ID.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Details of deleted user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: bad input parameter
          
  /users/editLastUpdated/{userid}:
    put:
      tags:
      - admins
      summary: Update Last Updated attribute of specified user
      description: Update Last Updated attribute of specified user
      operationId: edit_lastupdated
      parameters:
      - name: userid
        in: path
        description: User ID.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Details of updated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: bad input parameter
    

      
components:
  schemas:
    AllUsers:
      required:
      - user
      type: object
      properties:
        user: 
          type: array
          items:
            $ref: '#/components/schemas/User'
    User:
      required:
      - id
      - name
      - last_active
      type: object
      properties:
        id:
          type: string
          example: "jim_halpert"
        name:
          type: string
          example: "Jim Halpert"
        last_active:
          type: integer
          example: 1360031325
    AllMovies:
      type: object
      required:
        - movies
      properties:
        movies:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/MovieItem'
    MovieItem:
      type: object
      required:
        - title
        - rating
        - director
        - id
      properties:
        title:
          type: string
          example: The Martian
        rating:
          type: integer
          example: 7
        director:
          type: string
          example: Paul McGuigan
        id:
          type: string
          example: 39ab85e5-5e8e-4dc5-afea-65dc368bd7ab
